## 2003 Version
FROM nvcr.io/nvidia/tensorrt:20.03-py3

RUN sed -i -e 's/archive.ubuntu.com/free.nchc.org.tw/' /etc/apt/sources.list

# CUDA 10.2
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    ca-certificates wget sudo protobuf-compiler \
    libprotobuf-dev python3-pip curl vim zip && \
    rm -rf /var/lib/apt/lists/*
    # cuda-libraries-10-0

RUN /usr/bin/python3 -m pip install --upgrade pip

## install Pytorch
RUN pip3 install torch==1.5.0+cu101 torchvision==0.6.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
# RUN pip3 install torch torchvision -f https://download.pytorch.org/whl/torch_stable.html

## Onnxruntime by CPU version
# RUN pip3 install onnx==1.7.0 onnxruntime-gpu==1.1.2 
RUN pip3 install onnx==1.7.0 onnxruntime==1.4.0

## Install opencv
RUN pip3 install opencv-python==4.1.2.30 && pip3 install opencv-python-headless==4.1.2.30 
# RUN sudo apt-get update -y && sudo apt-get install -y libgl1-mesa-dev libglib2.0-0

## Install cuda-libraries-10-0 for onnxruntime-gpu use.
# RUN sudo apt-get update && sudo apt-get install -y software-properties-common && \
# sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub && \ 
# add-apt-repository "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /" && \
# sudo apt-get update && sudo apt-get -y install cuda-libraries-dev-10-0

## Install zsh
RUN ["apt-get", "update"]
RUN ["apt-get", "install", "-y", "zsh"]
RUN wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true

## Insatll Onnx2trt
# RUN git clone --recurse-submodules https://github.com/onnx/onnx-tensorrt.git && \
# cd onnx-tensorrt && git checkout release/7.0 && cmake . && make && make install 
# ENV LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH

## Install trtis client & matplotlib
RUN pip3 install tensorrtserver matplotlib