# Maintainer: Chieh

version: "3.8"
services:
  minio:
    image: minio/minio:RELEASE.2022-03-24T00-43-44Z
    shm_size: 20gb
    volumes:
      - ./data:/data:rw
      - ./config:/root/.minio
      - /etc/localtime:/etc/localtime:ro
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: user123456
    ports:
      - "9000:9000"
      - "9001:9001"
    container_name: minio
    command: server /data --console-address "0.0.0.0:9001"
    restart: always

volumes:
  data: {}
  config: {}

